// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/qdrant/go-client/qdrant"
	"log/slog"
	"model-gate/config"
	"model-gate/internal/api/modelgate"
	"model-gate/internal/pkg/embedding"
	"model-gate/internal/pkg/formater/answer"
	"model-gate/internal/pkg/model/processor"
	processor2 "model-gate/internal/pkg/vector/processor"
	clickhouse2 "model-gate/internal/repository/clickhouse"
	"model-gate/internal/repository/cookie"
	"model-gate/internal/repository/postgres"
	"model-gate/internal/usecase/category"
	modelgate2 "model-gate/internal/usecase/modelgate"
	http2 "model-gate/pkg/http"
	"net/http"
)

// Injectors from wire.go:

func InitializeApplicationAPI(logHandler slog.Handler, cfg *config.Config, client *http.Client, conn clickhouse.Conn, pool *pgxpool.Pool, qdrantClient *qdrant.Client) *modelgate.API {
	logger := slog.New(logHandler)
	dcHTTPClient := http2.NewDcHTTPClient(logger, client)
	factory := processor.NewFactory(dcHTTPClient, cfg, logger)
	embeddingFactory := embedding.NewFactory(dcHTTPClient, cfg, logger)
	processorFactory := processor2.NewFactory(qdrantClient, embeddingFactory, cfg, logger)
	strategyFactory := answer.NewStrategyFactory()
	vector := modelgate2.NewVector(processorFactory, cfg, logger, strategyFactory)
	getCategoryVariantUseCase := category.NewGetCategoryVariantUseCase(processorFactory, cfg, logger)
	chatUseCase := modelgate2.NewChatUseCase(factory, vector, getCategoryVariantUseCase, cfg)
	repository := postgres.NewRepository(pool)
	addChatUseCase := modelgate2.NewAddChatUseCase(repository)
	checkChatExistsUseCase := modelgate2.NewCheckChatExistsUseCase(repository)
	clickhouseRepository := clickhouse2.NewRepository(conn)
	addMessageUseCase := modelgate2.NewAddMessageUseCase(clickhouseRepository)
	messageListUseCase := modelgate2.NewMessageListUseCase(clickhouseRepository)
	metadataCookieProvider := cookie.NewMetadataCookieProvider()
	authUseCase := modelgate2.NewAuthUseCase(metadataCookieProvider)
	api := modelgate.NewAPI(chatUseCase, addChatUseCase, checkChatExistsUseCase, addMessageUseCase, messageListUseCase, authUseCase, cfg)
	return api
}
