syntax = "proto3";

package modelgate;

option go_package = "github.com/yeastor/modelgate/pkg/modelgate;modelgate";

import "google/api/annotations.proto";
import "validate/validate.proto";

message ChatResponse {
  ChatAnswer answer = 1;
}

message ChatAnswer {
  string content = 1;
}

message Chat {
  string id = 1;
}

message ChatQuestion {
  string q = 1;
}

message ChatBody {
  Chat chat = 1 [(validate.rules).message.required = true];
  ChatQuestion question = 2 [(validate.rules).message.required = true];
}

message ChatRequest {
  ChatBody chatBody = 1;
}
message CreateResponse {
  ChatAnswer note = 1;
}

message MessageListRequest {
  Chat chat = 1 [(validate.rules).message.required = true];
}

message MessageListResponse {
  repeated Message message = 1;
}

message Message {
  string text  = 1;
  string id = 2;
  int64 direction = 3;
}

// StartStart
message StartRequest {

}

message StartResponse {
  Chat chat = 1;
}

service ModelService {

  rpc Chat(ChatRequest) returns (ChatResponse) {
    option (google.api.http) = {
      post: "/model/chat/chat"
      body: "chatBody"
    };
  }

  rpc MessageList(MessageListRequest) returns (MessageListResponse) {
    option (google.api.http) = {
      post: "/model/chat/massage/list"
      body: "chat"
    };
  }

  rpc StartStart(StartRequest) returns (StartResponse) {
    option (google.api.http) = {
      post: "/model/chat/start/start"
    };
  }
}
